version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
test: off
artifacts:
- path: artifacts/*.nupkg
  name: Nuget Packages
deploy:
- provider: NuGet
  server: https://www.myget.org/F/discordrest
  api_key:
    secure: l2+tPFkwN+vS/l4hQurv2OdOuhaV9ZB9ZdOqbPalOumWNUL4kiyCn6M0ZpIbfkSz
  on:
    branch: dev